In [1]:
import pandas as pd 
import datetime
import numpy as np 

In [2]:
df = pd.read_csv('/content/Train_Data_Final.csv')
df1 = pd.read_csv('/content/Test_Data.csv')

In [3]:
df = pd.concat([df, df1])

In [4]:
df.head()

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  \
0  2004-03-10  18:00:00     2.6      1360.00       150  11.881723   
1  2004-03-10  19:00:00     2.0      1292.25       112   9.397165   
2  2004-03-10  20:00:00     2.2      1402.00        88   8.997817   
3  2004-03-10  21:00:00     2.2      1375.50        80   9.228796   
4  2004-03-10  22:00:00     1.6      1272.25        51   6.518224   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0        1045.50    166.0       1056.25    113.0       1692.00      1267.50   
1         954.75    103.0       1173.75     92.0       1558.75       972.25   
2         939.25    131.0       1140.00    114.0       1554.50      1074.00   
3         948.25    172.0       1092.00    122.0       1583.75      1203.25   
4         835.50    131.0       1205.00    116.0       1490.00      1110.00   

       T        AH            RH_type  id  Unnamed: 0  
0  13.60  0.757754              Ideal   1         NaN  
1  13.30  0.725487              Ideal   2         NaN  
2  11.90  0.750239  Slightly Elevated   3         NaN  
3  11.00  0.786713  Slightly Elevated   4         NaN  
4  11.15  0.788794  Slightly Elevated   5         NaN

In [5]:
duplicates = df.columns[df.columns.duplicated()]
print(duplicates)

Index([], dtype='object')


In [6]:
[df.columns]

[Index(['Date', 'Time', 'CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)',
        'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)',
        'PT08.S5(O3)', 'T', 'AH', 'RH_type', 'id', 'Unnamed: 0'],
       dtype='object')]

In [7]:
df['date_time'] = df['Date']+'T'+ df['Time']

In [8]:
df['date_time'].head()

0    2004-03-10T18:00:00
1    2004-03-10T19:00:00
2    2004-03-10T20:00:00
3    2004-03-10T21:00:00
4    2004-03-10T22:00:00
Name: date_time, dtype: object

In [9]:
df = df.drop(['Date', 'Time'], axis =1)

In [10]:
df

CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  PT08.S2(NMHC)  NOx(GT)  \
0        2.6      1360.00       150  11.881723        1045.50    166.0   
1        2.0      1292.25       112   9.397165         954.75    103.0   
2        2.2      1402.00        88   8.997817         939.25    131.0   
3        2.2      1375.50        80   9.228796         948.25    172.0   
4        1.6      1272.25        51   6.518224         835.50    131.0   
...      ...          ...       ...        ...            ...      ...   
1352     3.1      1314.25      -200  13.529605        1101.25    471.7   
1353     2.4      1162.50      -200  11.355157        1027.00    353.3   
1354     2.4      1142.00      -200  12.374538        1062.50    293.0   
1355     2.1      1002.50      -200   9.547187         960.50    234.5   
1356     2.2      1070.75      -200  11.932060        1047.25    265.2   

      PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)       T        AH  \
0          1056.25    113.0       1692.00      1267.50  13.600  0.757754   
1          1173.75     92.0       1558.75       972.25  13.300  0.725487   
2          1140.00    114.0       1554.50      1074.00  11.900  0.750239   
3          1092.00    122.0       1583.75      1203.25  11.000  0.786713   
4          1205.00    116.0       1490.00      1110.00  11.150  0.788794   
...            ...      ...           ...          ...     ...       ...   
1352        538.50    189.8       1374.25      1728.50  21.850  0.756824   
1353        603.75    179.2       1263.50      1269.00  24.325  0.711864   
1354        603.25    174.7       1240.75      1092.00  26.900  0.640649   
1355        701.50    155.7       1041.00       769.75  28.325  0.513866   
1356        654.00    167.7       1128.50       816.00  28.500  0.502804   

                RH_type    id  Unnamed: 0            date_time  
0                 Ideal     1         NaN  2004-03-10T18:00:00  
1                 Ideal     2         NaN  2004-03-10T19:00:00  
2     Slightly Elevated     3         NaN  2004-03-10T20:00:00  
3     Slightly Elevated     4         NaN  2004-03-10T21:00:00  
4     Slightly Elevated     5         NaN  2004-03-10T22:00:00  
...                 ...   ...         ...                  ...  
1352                NaN  1353      9352.0  2005-04-04T10:00:00  
1353                NaN  1354      9353.0  2005-04-04T11:00:00  
1354                NaN  1355      9354.0  2005-04-04T12:00:00  
1355                NaN  1356      9355.0  2005-04-04T13:00:00  
1356                NaN  1357      9356.0  2005-04-04T14:00:00  

[9357 rows x 16 columns]

In [11]:
duplicates = df.columns[df.columns.duplicated()]
print(duplicates)

Index([], dtype='object')


In [12]:
df['date_time'] = pd.to_datetime(df['date_time'], format='%Y-%m-%dT%H:%M:%S')

In [13]:
df['year'] = df['date_time'].dt.year
df['month'] = df['date_time'].dt.month
df['day'] = df['date_time'].dt.day
df['hour'] = df['date_time'].dt.hour
df['minute'] = df['date_time'].dt.minute
df['second'] = df['date_time'].dt.second

In [14]:
df = df.drop('date_time',axis = 1)

In [15]:
df['year'].unique()

array([2004, 2005])

In [16]:
df['month'].unique()

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2])

In [17]:
df['day'].unique()

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [18]:
df['hour'].unique()

array([18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11, 12, 13, 14, 15, 16, 17])

In [19]:
df['minute'].unique()

array([0])

In [20]:
df['second'].unique()

array([0])

In [21]:
df = df.drop(['minute', 'second', 'id'], axis = 1)

In [22]:
duplicates = df.columns[df.columns.duplicated()]
print(duplicates)

Index([], dtype='object')


In [23]:
df = pd.get_dummies(df, columns=['month', 'day', 'hour', 'year'])

In [24]:
duplicates = df.columns[df.columns.duplicated()]
print(duplicates)

Index([], dtype='object')


In [25]:
df

CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  PT08.S2(NMHC)  NOx(GT)  \
0        2.6      1360.00       150  11.881723        1045.50    166.0   
1        2.0      1292.25       112   9.397165         954.75    103.0   
2        2.2      1402.00        88   8.997817         939.25    131.0   
3        2.2      1375.50        80   9.228796         948.25    172.0   
4        1.6      1272.25        51   6.518224         835.50    131.0   
...      ...          ...       ...        ...            ...      ...   
1352     3.1      1314.25      -200  13.529605        1101.25    471.7   
1353     2.4      1162.50      -200  11.355157        1027.00    353.3   
1354     2.4      1142.00      -200  12.374538        1062.50    293.0   
1355     2.1      1002.50      -200   9.547187         960.50    234.5   
1356     2.2      1070.75      -200  11.932060        1047.25    265.2   

      PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  ...  hour_16  hour_17  \
0          1056.25    113.0       1692.00      1267.50  ...        0        0   
1          1173.75     92.0       1558.75       972.25  ...        0        0   
2          1140.00    114.0       1554.50      1074.00  ...        0        0   
3          1092.00    122.0       1583.75      1203.25  ...        0        0   
4          1205.00    116.0       1490.00      1110.00  ...        0        0   
...            ...      ...           ...          ...  ...      ...      ...   
1352        538.50    189.8       1374.25      1728.50  ...        0        0   
1353        603.75    179.2       1263.50      1269.00  ...        0        0   
1354        603.25    174.7       1240.75      1092.00  ...        0        0   
1355        701.50    155.7       1041.00       769.75  ...        0        0   
1356        654.00    167.7       1128.50       816.00  ...        0        0   

     hour_18  hour_19  hour_20  hour_21  hour_22  hour_23  year_2004  \
0          1        0        0        0        0        0          1   
1          0        1        0        0        0        0          1   
2          0        0        1        0        0        0          1   
3          0        0        0        1        0        0          1   
4          0        0        0        0        1        0          1   
...      ...      ...      ...      ...      ...      ...        ...   
1352       0        0        0        0        0        0          0   
1353       0        0        0        0        0        0          0   
1354       0        0        0        0        0        0          0   
1355       0        0        0        0        0        0          0   
1356       0        0        0        0        0        0          0   

      year_2005  
0             0  
1             0  
2             0  
3             0  
4             0  
...         ...  
1352          1  
1353          1  
1354          1  
1355          1  
1356          1  

[9357 rows x 83 columns]

In [26]:
duplicate_columns = df.columns[df.columns.duplicated()]

In [27]:
duplicate_columns

Index([], dtype='object')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9357 entries, 0 to 1356
Data columns (total 83 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   CO(GT)         9357 non-null   float64
 1   PT08.S1(CO)    9357 non-null   float64
 2   NMHC(GT)       9357 non-null   int64  
 3   C6H6(GT)       9357 non-null   float64
 4   PT08.S2(NMHC)  9357 non-null   float64
 5   NOx(GT)        9357 non-null   float64
 6   PT08.S3(NOx)   9357 non-null   float64
 7   NO2(GT)        9357 non-null   float64
 8   PT08.S4(NO2)   9357 non-null   float64
 9   PT08.S5(O3)    9357 non-null   float64
 10  T              9357 non-null   float64
 11  AH             9357 non-null   float64
 12  RH_type        8000 non-null   object 
 13  Unnamed: 0     1357 non-null   float64
 14  month_1        9357 non-null   uint8  
 15  month_2        9357 non-null   uint8  
 16  month_3        9357 non-null   uint8  
 17  month_4        9357 non-null   uint8  
 18  month_5 

In [29]:
df['RH_type'].unique()

array(['Ideal', 'Slightly Elevated', 'Elevated', 'High', 'Dry', nan],
      dtype=object)

In [30]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [31]:
df.groupby('RH_type').count()

CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  PT08.S2(NMHC)  \
RH_type                                                                     
Dry                  1570         1570      1570      1570           1570   
Elevated             1248         1248      1248      1248           1248   
High                  979          979       979       979            979   
Ideal                2673         2673      2673      2673           2673   
Slightly Elevated    1530         1530      1530      1530           1530   

                   NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
RH_type                                                                        
Dry                   1570          1570     1570          1570         1570   
Elevated              1248          1248     1248          1248         1248   
High                   979           979      979           979          979   
Ideal                 2673          2673     2673          2673         2673   
Slightly Elevated     1530          1530     1530          1530         1530   

                   ...  hour_16  hour_17  hour_18  hour_19  hour_20  hour_21  \
RH_type            ...                                                         
Dry                ...     1570     1570     1570     1570     1570     1570   
Elevated           ...     1248     1248     1248     1248     1248     1248   
High               ...      979      979      979      979      979      979   
Ideal              ...     2673     2673     2673     2673     2673     2673   
Slightly Elevated  ...     1530     1530     1530     1530     1530     1530   

                   hour_22  hour_23  year_2004  year_2005  
RH_type                                                    
Dry                   1570     1570       1570       1570  
Elevated              1248     1248       1248       1248  
High                   979      979        979        979  
Ideal                 2673     2673       2673       2673  
Slightly Elevated     1530     1530       1530       1530  

[5 rows x 82 columns]

In [32]:
le = LabelEncoder()
df['RH_type'] = le.fit_transform(df['RH_type'])

In [33]:
df['RH_type']

0       3
1       3
2       4
3       4
4       4
       ..
1352    5
1353    5
1354    5
1355    5
1356    5
Name: RH_type, Length: 9357, dtype: int64

In [34]:
df['RH_type'].unique()

array([3, 4, 1, 2, 0, 5])

In [35]:
df.isnull().sum()

CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         0
C6H6(GT)         0
PT08.S2(NMHC)    0
                ..
hour_21          0
hour_22          0
hour_23          0
year_2004        0
year_2005        0
Length: 83, dtype: int64

In [36]:
x = df.drop(["RH_type"],axis=1)
y = df['RH_type']

In [37]:
x_train, x_test = x[:8000], x[8000:] 
y_train, y_test = y[:8000], y[8000:]

In [38]:
y_train

0       3
1       3
2       4
3       4
4       4
       ..
7995    3
7996    3
7997    3
7998    3
7999    3
Name: RH_type, Length: 8000, dtype: int64

In [39]:
y_test

0       5
1       5
2       5
3       5
4       5
       ..
1352    5
1353    5
1354    5
1355    5
1356    5
Name: RH_type, Length: 1357, dtype: int64

In [40]:
x_train

CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  PT08.S2(NMHC)  NOx(GT)  \
0        2.6      1360.00       150  11.881723        1045.50    166.0   
1        2.0      1292.25       112   9.397165         954.75    103.0   
2        2.2      1402.00        88   8.997817         939.25    131.0   
3        2.2      1375.50        80   9.228796         948.25    172.0   
4        1.6      1272.25        51   6.518224         835.50    131.0   
...      ...          ...       ...        ...            ...      ...   
7995     1.4       937.50      -200   3.667817         692.00    192.9   
7996     1.1       896.25      -200   2.611733         627.00    157.8   
7997     1.0       907.25      -200   2.415395         613.75    149.8   
7998     1.1       902.25      -200   2.397211         612.50    130.3   
7999     1.0       885.00      -200   1.975190         582.25    104.3   

      PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  ...  hour_16  hour_17  \
0          1056.25    113.0       1692.00      1267.50  ...        0        0   
1          1173.75     92.0       1558.75       972.25  ...        0        0   
2          1140.00    114.0       1554.50      1074.00  ...        0        0   
3          1092.00    122.0       1583.75      1203.25  ...        0        0   
4          1205.00    116.0       1490.00      1110.00  ...        0        0   
...            ...      ...           ...          ...  ...      ...      ...   
7995        937.00    149.0        804.75       737.00  ...        0        0   
7996       1033.25    126.3        781.50       610.00  ...        0        0   
7997       1052.00    119.8        781.75       627.00  ...        0        0   
7998       1049.25    109.5        776.75       565.75  ...        0        0   
7999       1071.50     91.7        760.00       516.75  ...        0        0   

      hour_18  hour_19  hour_20  hour_21  hour_22  hour_23  year_2004  \
0           1        0        0        0        0        0          1   
1           0        1        0        0        0        0          1   
2           0        0        1        0        0        0          1   
3           0        0        0        1        0        0          1   
4           0        0        0        0        1        0          1   
...       ...      ...      ...      ...      ...      ...        ...   
7995        0        0        0        1        0        0          0   
7996        0        0        0        0        1        0          0   
7997        0        0        0        0        0        1          0   
7998        0        0        0        0        0        0          0   
7999        0        0        0        0        0        0          0   

      year_2005  
0             0  
1             0  
2             0  
3             0  
4             0  
...         ...  
7995          1  
7996          1  
7997          1  
7998          1  
7999          1  

[8000 rows x 82 columns]

In [41]:
x_train.isnull().sum()

CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         0
C6H6(GT)         0
PT08.S2(NMHC)    0
                ..
hour_21          0
hour_22          0
hour_23          0
year_2004        0
year_2005        0
Length: 82, dtype: int64

In [42]:
x_test.isnull().sum()

CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         0
C6H6(GT)         0
PT08.S2(NMHC)    0
                ..
hour_21          0
hour_22          0
hour_23          0
year_2004        0
year_2005        0
Length: 82, dtype: int64

In [43]:
y_train.isnull().sum()

0

In [44]:
y_train.isnull().sum()

0

In [45]:
x_test

CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  PT08.S2(NMHC)  NOx(GT)  \
0        0.8       863.00      -200   1.504175         545.00     85.6   
1        0.6       860.75      -200   1.200205         518.25   -200.0   
2        0.6       852.25      -200   0.831325         481.50     66.6   
3        0.6       879.25      -200   0.962585         495.25     75.1   
4        0.6       899.50      -200   1.268602         524.50     96.9   
...      ...          ...       ...        ...            ...      ...   
1352     3.1      1314.25      -200  13.529605        1101.25    471.7   
1353     2.4      1162.50      -200  11.355157        1027.00    353.3   
1354     2.4      1142.00      -200  12.374538        1062.50    293.0   
1355     2.1      1002.50      -200   9.547187         960.50    234.5   
1356     2.2      1070.75      -200  11.932060        1047.25    265.2   

      PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  ...  hour_16  hour_17  \
0          1119.25     78.4        748.75       483.50  ...        0        0   
1          1140.75   -200.0        737.50       481.50  ...        0        0   
2          1186.50     65.1        725.75       496.00  ...        0        0   
3          1146.50     72.5        752.75       622.75  ...        0        0   
4          1090.00     84.6        780.25       695.75  ...        0        0   
...            ...      ...           ...          ...  ...      ...      ...   
1352        538.50    189.8       1374.25      1728.50  ...        0        0   
1353        603.75    179.2       1263.50      1269.00  ...        0        0   
1354        603.25    174.7       1240.75      1092.00  ...        0        0   
1355        701.50    155.7       1041.00       769.75  ...        0        0   
1356        654.00    167.7       1128.50       816.00  ...        0        0   

      hour_18  hour_19  hour_20  hour_21  hour_22  hour_23  year_2004  \
0           0        0        0        0        0        0          0   
1           0        0        0        0        0        0          0   
2           0        0        0        0        0        0          0   
3           0        0        0        0        0        0          0   
4           0        0        0        0        0        0          0   
...       ...      ...      ...      ...      ...      ...        ...   
1352        0        0        0        0        0        0          0   
1353        0        0        0        0        0        0          0   
1354        0        0        0        0        0        0          0   
1355        0        0        0        0        0        0          0   
1356        0        0        0        0        0        0          0   

      year_2005  
0             1  
1             1  
2             1  
3             1  
4             1  
...         ...  
1352          1  
1353          1  
1354          1  
1355          1  
1356          1  

[1357 rows x 82 columns]

In [46]:
y_test

0       5
1       5
2       5
3       5
4       5
       ..
1352    5
1353    5
1354    5
1355    5
1356    5
Name: RH_type, Length: 1357, dtype: int64

In [47]:
y_train = y_train.values.reshape(-1,1)
y_test = y_test.values.reshape(-1,1)

In [48]:
x_train

CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  PT08.S2(NMHC)  NOx(GT)  \
0        2.6      1360.00       150  11.881723        1045.50    166.0   
1        2.0      1292.25       112   9.397165         954.75    103.0   
2        2.2      1402.00        88   8.997817         939.25    131.0   
3        2.2      1375.50        80   9.228796         948.25    172.0   
4        1.6      1272.25        51   6.518224         835.50    131.0   
...      ...          ...       ...        ...            ...      ...   
7995     1.4       937.50      -200   3.667817         692.00    192.9   
7996     1.1       896.25      -200   2.611733         627.00    157.8   
7997     1.0       907.25      -200   2.415395         613.75    149.8   
7998     1.1       902.25      -200   2.397211         612.50    130.3   
7999     1.0       885.00      -200   1.975190         582.25    104.3   

      PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  ...  hour_16  hour_17  \
0          1056.25    113.0       1692.00      1267.50  ...        0        0   
1          1173.75     92.0       1558.75       972.25  ...        0        0   
2          1140.00    114.0       1554.50      1074.00  ...        0        0   
3          1092.00    122.0       1583.75      1203.25  ...        0        0   
4          1205.00    116.0       1490.00      1110.00  ...        0        0   
...            ...      ...           ...          ...  ...      ...      ...   
7995        937.00    149.0        804.75       737.00  ...        0        0   
7996       1033.25    126.3        781.50       610.00  ...        0        0   
7997       1052.00    119.8        781.75       627.00  ...        0        0   
7998       1049.25    109.5        776.75       565.75  ...        0        0   
7999       1071.50     91.7        760.00       516.75  ...        0        0   

      hour_18  hour_19  hour_20  hour_21  hour_22  hour_23  year_2004  \
0           1        0        0        0        0        0          1   
1           0        1        0        0        0        0          1   
2           0        0        1        0        0        0          1   
3           0        0        0        1        0        0          1   
4           0        0        0        0        1        0          1   
...       ...      ...      ...      ...      ...      ...        ...   
7995        0        0        0        1        0        0          0   
7996        0        0        0        0        1        0          0   
7997        0        0        0        0        0        1          0   
7998        0        0        0        0        0        0          0   
7999        0        0        0        0        0        0          0   

      year_2005  
0             0  
1             0  
2             0  
3             0  
4             0  
...         ...  
7995          1  
7996          1  
7997          1  
7998          1  
7999          1  

[8000 rows x 82 columns]

In [49]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/extmath.py:1047: RuntimeWarning: invalid value encountered in true_divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/usr/local/lib/python3.9/dist-packages/sklearn/utils/extmath.py:1052: RuntimeWarning: invalid value encountered in true_divide
  T = new_sum / new_sample_count
/usr/local/lib/python3.9/dist-packages/sklearn/utils/extmath.py:1072: RuntimeWarning: invalid value encountered in true_divide
  new_unnormalized_variance -= correction**2 / new_sample_count


In [50]:
np.isnan(x_train.any())

False

In [51]:
np.isfinite(x_train.all())

True

In [52]:
from sklearn.ensemble import HistGradientBoostingClassifier

In [53]:
clf = HistGradientBoostingClassifier().fit(x_train, y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [54]:
clf.score(x_train, y_train)

1.0

In [55]:
prediction = clf.predict(x_test)

In [56]:
predictions_test = le.inverse_transform(prediction)

In [57]:
predictions_test

array(['High', 'High', 'High', ..., 'Ideal', 'Ideal', 'Ideal'],
      dtype=object)

In [58]:
predictions_test.reshape(-1,1)

array([['High'],
       ['High'],
       ['High'],
       ...,
       ['Ideal'],
       ['Ideal'],
       ['Ideal']], dtype=object)

In [59]:
predictions_test = pd.DataFrame(predictions_test)

In [60]:
predictions_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1357 entries, 0 to 1356
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       1357 non-null   object
dtypes: object(1)
memory usage: 10.7+ KB


In [61]:
predictions_test.rename( columns={0 :'RH_type'}, inplace=True ) 

In [62]:
predictions_test

RH_type
0       High
1       High
2       High
3       High
4       High
...      ...
1352   Ideal
1353   Ideal
1354   Ideal
1355   Ideal
1356   Ideal

[1357 rows x 1 columns]